// <auto-generated />
using System;
using FichaOnline.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FichaOnline.Migrations
{
    [DbContext(typeof(ContextoDb))]
    [Migration("20231031233009_Relacionamento-Ficha")]
    partial class RelacionamentoFicha
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FichaOnline.Models.TBBairro", b =>
                {
                    b.Property<int>("BairroId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BairroId"));

                    b.Property<DateTime?>("BairroAltEm")
                        .HasColumnType("datetime2");

                    b.Property<int?>("BairroAltPor")
                        .HasColumnType("int");

                    b.Property<DateTime>("BairroIncEm")
                        .HasColumnType("datetime2");

                    b.Property<int>("BairroIncPor")
                        .HasColumnType("int");

                    b.Property<string>("BairroNome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CidadeId")
                        .HasColumnType("int");

                    b.HasKey("BairroId");

                    b.HasIndex("CidadeId");

                    b.ToTable("TBAIRRO");
                });

            modelBuilder.Entity("FichaOnline.Models.TBCidade", b =>
                {
                    b.Property<int>("CidId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CidId"));

                    b.Property<DateTime?>("CidAltEm")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CidAltPor")
                        .HasColumnType("int");

                    b.Property<long?>("CidCodIbge")
                        .HasColumnType("bigint");

                    b.Property<int?>("CidIdDistrito")
                        .HasColumnType("int");

                    b.Property<DateTime>("CidIncEm")
                        .HasColumnType("datetime2");

                    b.Property<int>("CidIncPor")
                        .HasColumnType("int");

                    b.Property<string>("CidNom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CidNomDistrito")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CidTipo")
                        .HasColumnType("int");

                    b.Property<int>("EstId")
                        .HasColumnType("int");

                    b.HasKey("CidId");

                    b.HasIndex("EstId");

                    b.ToTable("TBCIDADE");
                });

            modelBuilder.Entity("FichaOnline.Models.TBEstado", b =>
                {
                    b.Property<int>("EstId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EstId"));

                    b.Property<DateTime?>("EstAltEm")
                        .HasColumnType("datetime2");

                    b.Property<int?>("EstAltPor")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EstIncEm")
                        .HasColumnType("datetime2");

                    b.Property<int>("EstIncPor")
                        .HasColumnType("int");

                    b.Property<string>("EstNom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EstSgl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EstId");

                    b.ToTable("TBESTADO");
                });

            modelBuilder.Entity("FichaOnline.Models.TBPerfilaAcesso", b =>
                {
                    b.Property<int>("PerfilAcessoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PerfilAcessoId"));

                    b.Property<DateTime?>("PerfilAcessoAltEm")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PerfilAcessoAltPor")
                        .HasColumnType("int");

                    b.Property<string>("PerfilAcessoDesc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PerfilAcessoIncEm")
                        .HasColumnType("datetime2");

                    b.Property<int>("PerfilAcessoIncPor")
                        .HasColumnType("int");

                    b.Property<short>("PerfilAcessoNivel")
                        .HasColumnType("smallint");

                    b.HasKey("PerfilAcessoId");

                    b.ToTable("TBPERFILACESSO");
                });

            modelBuilder.Entity("FichaOnline.Models.TBPolo", b =>
                {
                    b.Property<int>("PoloId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PoloId"));

                    b.Property<DateTime?>("PoloAltEm")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PoloAltPor")
                        .HasColumnType("int");

                    b.Property<DateTime>("PoloIncEm")
                        .HasColumnType("datetime2");

                    b.Property<int>("PoloIncPor")
                        .HasColumnType("int");

                    b.Property<string>("PoloNome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PoloStatus")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PoloId");

                    b.ToTable("TBPOLO");
                });

            modelBuilder.Entity("FichaOnline.Models.TBUnidadeTipos", b =>
                {
                    b.Property<int>("UnidadeTpoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UnidadeTpoId"));

                    b.Property<string>("UnidadeSgl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnidadeTipo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UnidadeTpoAltEm")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UnidadeTpoAltPor")
                        .HasColumnType("int");

                    b.Property<string>("UnidadeTpoDsc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UnidadeTpoIncEm")
                        .HasColumnType("datetime2");

                    b.Property<int>("UnidadeTpoIncPor")
                        .HasColumnType("int");

                    b.HasKey("UnidadeTpoId");

                    b.ToTable("TBUNIDADETIPOS");
                });

            modelBuilder.Entity("FichaOnline.Models.TBUnidades", b =>
                {
                    b.Property<int>("UnidadeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UnidadeId"));

                    b.Property<int>("PoloId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UnidadeAltEm")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UnidadeAltPor")
                        .HasColumnType("int");

                    b.Property<string>("UnidadeCEP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UnidadeCod")
                        .HasColumnType("int");

                    b.Property<string>("UnidadeDDD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnidadeDesc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnidadeEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnidadeEndComp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnidadeEndLog")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnidadeEndNmr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnidadeFone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UnidadeIncEm")
                        .HasColumnType("datetime2");

                    b.Property<int>("UnidadeIncPor")
                        .HasColumnType("int");

                    b.Property<string>("UnidadeStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UnidadesTpoId")
                        .HasColumnType("int");

                    b.HasKey("UnidadeId");

                    b.HasIndex("PoloId");

                    b.HasIndex("UnidadesTpoId");

                    b.ToTable("TBUNIDADES");
                });

            modelBuilder.Entity("FichaOnline.Models.TBUsuarios", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuarioId"));

                    b.Property<int>("PerfilAcessoId")
                        .HasColumnType("int");

                    b.Property<int>("UnidadeId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UsuarioAltEm")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UsuarioAltPor")
                        .HasColumnType("int");

                    b.Property<string>("UsuarioCpf")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("UsuarioEmailTran")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("UsuarioIncEm")
                        .HasColumnType("datetime2");

                    b.Property<int>("UsuarioIncPor")
                        .HasColumnType("int");

                    b.Property<string>("UsuarioNome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioSenha")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UsuarioSenhaTemp")
                        .HasColumnType("int");

                    b.Property<string>("UsuarioStatus")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UsuarioId");

                    b.HasIndex("PerfilAcessoId");

                    b.HasIndex("UnidadeId");

                    b.ToTable("TBUSUARIOS");
                });

            modelBuilder.Entity("FichaOnline.Models.TBBairro", b =>
                {
                    b.HasOne("FichaOnline.Models.TBCidade", "BairroCidade")
                        .WithMany("CidadeBairros")
                        .HasForeignKey("CidadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BairroCidade");
                });

            modelBuilder.Entity("FichaOnline.Models.TBCidade", b =>
                {
                    b.HasOne("FichaOnline.Models.TBEstado", "CidEstado")
                        .WithMany("EstadoCidades")
                        .HasForeignKey("EstId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CidEstado");
                });

            modelBuilder.Entity("FichaOnline.Models.TBUnidades", b =>
                {
                    b.HasOne("FichaOnline.Models.TBPolo", "Polo")
                        .WithMany("UnidadePolos")
                        .HasForeignKey("PoloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FichaOnline.Models.TBUnidadeTipos", "TiposUnidade")
                        .WithMany("UnidadeUnidadeTipos")
                        .HasForeignKey("UnidadesTpoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Polo");

                    b.Navigation("TiposUnidade");
                });

            modelBuilder.Entity("FichaOnline.Models.TBUsuarios", b =>
                {
                    b.HasOne("FichaOnline.Models.TBPerfilaAcesso", "PerfilAcesso")
                        .WithMany("Usuarios")
                        .HasForeignKey("PerfilAcessoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FichaOnline.Models.TBUnidades", "Unidades")
                        .WithMany("UnidadeUsuarios")
                        .HasForeignKey("UnidadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PerfilAcesso");

                    b.Navigation("Unidades");
                });

            modelBuilder.Entity("FichaOnline.Models.TBCidade", b =>
                {
                    b.Navigation("CidadeBairros");
                });

            modelBuilder.Entity("FichaOnline.Models.TBEstado", b =>
                {
                    b.Navigation("EstadoCidades");
                });

            modelBuilder.Entity("FichaOnline.Models.TBPerfilaAcesso", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("FichaOnline.Models.TBPolo", b =>
                {
                    b.Navigation("UnidadePolos");
                });

            modelBuilder.Entity("FichaOnline.Models.TBUnidadeTipos", b =>
                {
                    b.Navigation("UnidadeUnidadeTipos");
                });

            modelBuilder.Entity("FichaOnline.Models.TBUnidades", b =>
                {
                    b.Navigation("UnidadeUsuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
