// <auto-generated />
using System;
using FichaOnline.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FichaOnline.Migrations
{
    [DbContext(typeof(ContextoDb))]
    [Migration("20231010211118_Criacao-tabelas-usuario")]
    partial class Criacaotabelasusuario
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FichaOnline.Models.Tbperfilacesso", b =>
                {
                    b.Property<int>("PerfilAcessoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PerfilAcessoId"));

                    b.Property<DateTime?>("PerfilAcessoAltEm")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PerfilAcessoAltPor")
                        .HasColumnType("int");

                    b.Property<string>("PerfilAcessoDesc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PerfilAcessoIncEm")
                        .HasColumnType("datetime2");

                    b.Property<int>("PerfilAcessoIncPor")
                        .HasColumnType("int");

                    b.Property<short>("PerfilAcessoNivel")
                        .HasColumnType("smallint");

                    b.HasKey("PerfilAcessoId");

                    b.ToTable("TBPERFILACESSO");
                });

            modelBuilder.Entity("FichaOnline.Models.Tbusuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuarioId"));

                    b.Property<int>("PerfilAcessoId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UsuarioAltEm")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UsuarioAltPor")
                        .HasColumnType("int");

                    b.Property<string>("UsuarioCpf")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("UsuarioEmailTran")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("UsuarioIncEm")
                        .HasColumnType("datetime2");

                    b.Property<int>("UsuarioIncPor")
                        .HasColumnType("int");

                    b.Property<string>("UsuarioNome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioSenha")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioSenhaTemp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioStatus")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UsuarioId");

                    b.HasIndex("PerfilAcessoId")
                        .IsUnique();

                    b.ToTable("TBUSUARIO");
                });

            modelBuilder.Entity("FichaOnline.Models.Tbusuario", b =>
                {
                    b.HasOne("FichaOnline.Models.Tbperfilacesso", "PerfilAcesso")
                        .WithOne("Usuario")
                        .HasForeignKey("FichaOnline.Models.Tbusuario", "PerfilAcessoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PerfilAcesso");
                });

            modelBuilder.Entity("FichaOnline.Models.Tbperfilacesso", b =>
                {
                    b.Navigation("Usuario");
                });
#pragma warning restore 612, 618
        }
    }
}
