// <auto-generated />
using System;
using FichaOnline.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FichaOnline.Migrations
{
    [DbContext(typeof(ContextoDb))]
    [Migration("20231105213012_adiconando-camposNULL2")]
    partial class adiconandocamposNULL2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FichaOnline.Models.TBAluno", b =>
                {
                    b.Property<int>("AluId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AluId"));

                    b.Property<DateTime?>("AluAltEm")
                        .HasColumnType("datetime2");

                    b.Property<int?>("AluAltPor")
                        .HasColumnType("int");

                    b.Property<string>("AluCpf")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("AluDtaNasc")
                        .HasColumnType("datetime2");

                    b.Property<string>("AluEndBairro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AluEndCep")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AluEndCmpLog")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AluEndLog")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AluEndNmrLog")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AluFiliacao1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AluFiliacao2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AluFiliacao3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("AluIdinep")
                        .HasColumnType("int");

                    b.Property<DateTime>("AluIncEm")
                        .HasColumnType("datetime2");

                    b.Property<int>("AluIncPor")
                        .HasColumnType("int");

                    b.Property<string>("AluNom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AluNomSoc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AluObs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AluRaca")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AluSexo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AluStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AluTelCel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AluTelCelDdd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AluTelCon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AluTelConDdd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AluTelRes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AluTelResDdd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("BairroId")
                        .HasColumnType("int");

                    b.Property<int>("GedAluCod")
                        .HasColumnType("int");

                    b.HasKey("AluId");

                    b.HasIndex("BairroId");

                    b.ToTable("TBALUNO");
                });

            modelBuilder.Entity("FichaOnline.Models.TBBairro", b =>
                {
                    b.Property<int>("BairroId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BairroId"));

                    b.Property<DateTime?>("BairroAltEm")
                        .HasColumnType("datetime2");

                    b.Property<int?>("BairroAltPor")
                        .HasColumnType("int");

                    b.Property<DateTime>("BairroIncEm")
                        .HasColumnType("datetime2");

                    b.Property<int>("BairroIncPor")
                        .HasColumnType("int");

                    b.Property<string>("BairroNome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CidadeId")
                        .HasColumnType("int");

                    b.HasKey("BairroId");

                    b.HasIndex("CidadeId");

                    b.ToTable("TBBAIRRO");
                });

            modelBuilder.Entity("FichaOnline.Models.TBCategoria", b =>
                {
                    b.Property<int>("CatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CatId"));

                    b.Property<DateTime?>("CatAltEm")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CatAltPor")
                        .HasColumnType("int");

                    b.Property<string>("CatDesc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CatIncEm")
                        .HasColumnType("datetime2");

                    b.Property<int>("CatIncPor")
                        .HasColumnType("int");

                    b.Property<string>("CatSts")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CatId");

                    b.ToTable("TBCATEGORIA");
                });

            modelBuilder.Entity("FichaOnline.Models.TBCategoriaOpcoes", b =>
                {
                    b.Property<int>("CatOpcId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CatOpcId"));

                    b.Property<int>("CatId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CatOpcAltEm")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CatOpcAltPor")
                        .HasColumnType("int");

                    b.Property<string>("CatOpcDesc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CatOpcIncEm")
                        .HasColumnType("datetime2");

                    b.Property<int>("CatOpcIncPor")
                        .HasColumnType("int");

                    b.Property<bool>("Selecionado")
                        .HasColumnType("bit");

                    b.HasKey("CatOpcId");

                    b.HasIndex("CatId");

                    b.ToTable("TBCATEGORIAOPCOES");
                });

            modelBuilder.Entity("FichaOnline.Models.TBCidade", b =>
                {
                    b.Property<int>("CidId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CidId"));

                    b.Property<DateTime?>("CidAltEm")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CidAltPor")
                        .HasColumnType("int");

                    b.Property<long?>("CidCodIbge")
                        .HasColumnType("bigint");

                    b.Property<int?>("CidIdDistrito")
                        .HasColumnType("int");

                    b.Property<DateTime>("CidIncEm")
                        .HasColumnType("datetime2");

                    b.Property<int>("CidIncPor")
                        .HasColumnType("int");

                    b.Property<string>("CidNom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CidNomDistrito")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CidTipo")
                        .HasColumnType("int");

                    b.Property<int>("EstId")
                        .HasColumnType("int");

                    b.HasKey("CidId");

                    b.HasIndex("EstId");

                    b.ToTable("TBCIDADE");
                });

            modelBuilder.Entity("FichaOnline.Models.TBEstado", b =>
                {
                    b.Property<int>("EstId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EstId"));

                    b.Property<DateTime?>("EstAltEm")
                        .HasColumnType("datetime2");

                    b.Property<int?>("EstAltPor")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EstIncEm")
                        .HasColumnType("datetime2");

                    b.Property<int>("EstIncPor")
                        .HasColumnType("int");

                    b.Property<string>("EstNom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EstSgl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EstId");

                    b.ToTable("TBESTADO");
                });

            modelBuilder.Entity("FichaOnline.Models.TBFicha", b =>
                {
                    b.Property<int>("FichaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FichaId"));

                    b.Property<int>("AluId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FichaAltEm")
                        .HasColumnType("datetime2");

                    b.Property<int?>("FichaAltPor")
                        .HasColumnType("int");

                    b.Property<int>("FichaAtualUnidadeId")
                        .HasColumnType("int");

                    b.Property<int>("FichaCatId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FichaDtaFim")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FichaDtaIni")
                        .HasColumnType("datetime2");

                    b.Property<int>("FichaEscOrigemUnidadeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FichaIncEm")
                        .HasColumnType("datetime2");

                    b.Property<int>("FichaIncPor")
                        .HasColumnType("int");

                    b.Property<string>("FichaNova")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FichaStsId")
                        .HasColumnType("int");

                    b.HasKey("FichaId");

                    b.HasIndex("AluId");

                    b.HasIndex("FichaCatId");

                    b.HasIndex("FichaEscOrigemUnidadeId");

                    b.ToTable("TBFICHA");
                });

            modelBuilder.Entity("FichaOnline.Models.TBFichaCategoriaOpcResp", b =>
                {
                    b.Property<int>("FichaCatOpcRespId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FichaCatOpcRespId"));

                    b.Property<int?>("CatOpcId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FichaCatOpcIncEm")
                        .HasColumnType("datetime2");

                    b.Property<int>("FichaCatOpcResIncPor")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FichaCatOpcRespAltEm")
                        .HasColumnType("datetime2");

                    b.Property<int?>("FichaCatOpcRespAltPor")
                        .HasColumnType("int");

                    b.Property<int?>("FichaId")
                        .HasColumnType("int");

                    b.HasKey("FichaCatOpcRespId");

                    b.HasIndex("CatOpcId");

                    b.HasIndex("FichaId");

                    b.ToTable("TBCATEGORIAOPCRESP");
                });

            modelBuilder.Entity("FichaOnline.Models.TBFichaProvidenciasResp", b =>
                {
                    b.Property<int>("FichaProvRespId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FichaProvRespId"));

                    b.Property<DateTime?>("FichaDataTramitacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("FichaDefineRetorno")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FichaDtaComunicRespons")
                        .HasColumnType("datetime2");

                    b.Property<int>("FichaId")
                        .HasColumnType("int");

                    b.Property<int?>("FichaMeioComunic")
                        .HasColumnType("int");

                    b.Property<string>("FichaPorQuemUsuariorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FichaPraQuemUsuariorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FichaProcedimentoUnidade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FichaProvRespAltPor")
                        .HasColumnType("int");

                    b.Property<DateTime>("FichaProvRespIncEm")
                        .HasColumnType("datetime2");

                    b.Property<int>("FichaProvRespIncPor")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FichaRecebidoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FichaprovRespAltEm")
                        .HasColumnType("datetime2");

                    b.HasKey("FichaProvRespId");

                    b.HasIndex("FichaId");

                    b.ToTable("TBFICHAPROVIDENCIASRESP");
                });

            modelBuilder.Entity("FichaOnline.Models.TBPerfilaAcesso", b =>
                {
                    b.Property<int>("PerfilAcessoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PerfilAcessoId"));

                    b.Property<DateTime?>("PerfilAcessoAltEm")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PerfilAcessoAltPor")
                        .HasColumnType("int");

                    b.Property<string>("PerfilAcessoDesc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PerfilAcessoIncEm")
                        .HasColumnType("datetime2");

                    b.Property<int>("PerfilAcessoIncPor")
                        .HasColumnType("int");

                    b.Property<short>("PerfilAcessoNivel")
                        .HasColumnType("smallint");

                    b.HasKey("PerfilAcessoId");

                    b.ToTable("TBPERFILACESSO");
                });

            modelBuilder.Entity("FichaOnline.Models.TBPolo", b =>
                {
                    b.Property<int>("PoloId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PoloId"));

                    b.Property<DateTime?>("PoloAltEm")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PoloAltPor")
                        .HasColumnType("int");

                    b.Property<DateTime>("PoloIncEm")
                        .HasColumnType("datetime2");

                    b.Property<int>("PoloIncPor")
                        .HasColumnType("int");

                    b.Property<string>("PoloNome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PoloStatus")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PoloId");

                    b.ToTable("TBPOLO");
                });

            modelBuilder.Entity("FichaOnline.Models.TBUnidadeTipos", b =>
                {
                    b.Property<int>("UnidadeTpoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UnidadeTpoId"));

                    b.Property<string>("UnidadeSgl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnidadeTipo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UnidadeTpoAltEm")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UnidadeTpoAltPor")
                        .HasColumnType("int");

                    b.Property<string>("UnidadeTpoDsc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UnidadeTpoIncEm")
                        .HasColumnType("datetime2");

                    b.Property<int>("UnidadeTpoIncPor")
                        .HasColumnType("int");

                    b.HasKey("UnidadeTpoId");

                    b.ToTable("TBUNIDADETIPOS");
                });

            modelBuilder.Entity("FichaOnline.Models.TBUnidades", b =>
                {
                    b.Property<int>("UnidadeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UnidadeId"));

                    b.Property<int>("PoloId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UnidadeAltEm")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UnidadeAltPor")
                        .HasColumnType("int");

                    b.Property<string>("UnidadeCEP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UnidadeCod")
                        .HasColumnType("int");

                    b.Property<string>("UnidadeDDD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnidadeDesc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnidadeEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnidadeEndComp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnidadeEndLog")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnidadeEndNmr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnidadeFone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UnidadeIncEm")
                        .HasColumnType("datetime2");

                    b.Property<int>("UnidadeIncPor")
                        .HasColumnType("int");

                    b.Property<string>("UnidadeStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UnidadesTpoId")
                        .HasColumnType("int");

                    b.HasKey("UnidadeId");

                    b.HasIndex("PoloId");

                    b.HasIndex("UnidadesTpoId");

                    b.ToTable("TBUNIDADES");
                });

            modelBuilder.Entity("FichaOnline.Models.TBUsuarios", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuarioId"));

                    b.Property<int>("PerfilAcessoId")
                        .HasColumnType("int");

                    b.Property<int>("UnidadeId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UsuarioAltEm")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UsuarioAltPor")
                        .HasColumnType("int");

                    b.Property<string>("UsuarioCpf")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("UsuarioEmailTran")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("UsuarioIncEm")
                        .HasColumnType("datetime2");

                    b.Property<int>("UsuarioIncPor")
                        .HasColumnType("int");

                    b.Property<string>("UsuarioNome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioSenha")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UsuarioSenhaTemp")
                        .HasColumnType("int");

                    b.Property<string>("UsuarioStatus")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UsuarioId");

                    b.HasIndex("PerfilAcessoId");

                    b.HasIndex("UnidadeId");

                    b.ToTable("TBUSUARIOS");
                });

            modelBuilder.Entity("FichaOnline.Models.TBAluno", b =>
                {
                    b.HasOne("FichaOnline.Models.TBBairro", "AlunoBairro")
                        .WithMany("BairroAlunos")
                        .HasForeignKey("BairroId");

                    b.Navigation("AlunoBairro");
                });

            modelBuilder.Entity("FichaOnline.Models.TBBairro", b =>
                {
                    b.HasOne("FichaOnline.Models.TBCidade", "BairroCidade")
                        .WithMany("CidadeBairros")
                        .HasForeignKey("CidadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BairroCidade");
                });

            modelBuilder.Entity("FichaOnline.Models.TBCategoriaOpcoes", b =>
                {
                    b.HasOne("FichaOnline.Models.TBCategoria", "Categoria")
                        .WithMany("CategoriaCategoriaOpcoes")
                        .HasForeignKey("CatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("FichaOnline.Models.TBCidade", b =>
                {
                    b.HasOne("FichaOnline.Models.TBEstado", "CidEstado")
                        .WithMany("EstadoCidades")
                        .HasForeignKey("EstId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CidEstado");
                });

            modelBuilder.Entity("FichaOnline.Models.TBFicha", b =>
                {
                    b.HasOne("FichaOnline.Models.TBAluno", "FichaAluno")
                        .WithMany("AlunoFicha")
                        .HasForeignKey("AluId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FichaOnline.Models.TBCategoria", "FichaCategoria")
                        .WithMany("CategoriaFicha")
                        .HasForeignKey("FichaCatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FichaOnline.Models.TBUnidades", "FichaEscOrigemUnidade")
                        .WithMany()
                        .HasForeignKey("FichaEscOrigemUnidadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FichaAluno");

                    b.Navigation("FichaCategoria");

                    b.Navigation("FichaEscOrigemUnidade");
                });

            modelBuilder.Entity("FichaOnline.Models.TBFichaCategoriaOpcResp", b =>
                {
                    b.HasOne("FichaOnline.Models.TBCategoriaOpcoes", "CatOpcRespCatOpc")
                        .WithMany("FichaCategoriaOpcResps")
                        .HasForeignKey("CatOpcId");

                    b.HasOne("FichaOnline.Models.TBFicha", "CatOpcRespFicha")
                        .WithMany("FichaCatOpcResp")
                        .HasForeignKey("FichaId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("CatOpcRespCatOpc");

                    b.Navigation("CatOpcRespFicha");
                });

            modelBuilder.Entity("FichaOnline.Models.TBFichaProvidenciasResp", b =>
                {
                    b.HasOne("FichaOnline.Models.TBFicha", "FichaProvFicha")
                        .WithMany("FichaFichaProv")
                        .HasForeignKey("FichaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FichaProvFicha");
                });

            modelBuilder.Entity("FichaOnline.Models.TBUnidades", b =>
                {
                    b.HasOne("FichaOnline.Models.TBPolo", "Polo")
                        .WithMany("UnidadePolos")
                        .HasForeignKey("PoloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FichaOnline.Models.TBUnidadeTipos", "TiposUnidade")
                        .WithMany("UnidadeUnidadeTipos")
                        .HasForeignKey("UnidadesTpoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Polo");

                    b.Navigation("TiposUnidade");
                });

            modelBuilder.Entity("FichaOnline.Models.TBUsuarios", b =>
                {
                    b.HasOne("FichaOnline.Models.TBPerfilaAcesso", "PerfilAcesso")
                        .WithMany("Usuarios")
                        .HasForeignKey("PerfilAcessoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FichaOnline.Models.TBUnidades", "Unidades")
                        .WithMany("UnidadeUsuarios")
                        .HasForeignKey("UnidadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PerfilAcesso");

                    b.Navigation("Unidades");
                });

            modelBuilder.Entity("FichaOnline.Models.TBAluno", b =>
                {
                    b.Navigation("AlunoFicha");
                });

            modelBuilder.Entity("FichaOnline.Models.TBBairro", b =>
                {
                    b.Navigation("BairroAlunos");
                });

            modelBuilder.Entity("FichaOnline.Models.TBCategoria", b =>
                {
                    b.Navigation("CategoriaCategoriaOpcoes");

                    b.Navigation("CategoriaFicha");
                });

            modelBuilder.Entity("FichaOnline.Models.TBCategoriaOpcoes", b =>
                {
                    b.Navigation("FichaCategoriaOpcResps");
                });

            modelBuilder.Entity("FichaOnline.Models.TBCidade", b =>
                {
                    b.Navigation("CidadeBairros");
                });

            modelBuilder.Entity("FichaOnline.Models.TBEstado", b =>
                {
                    b.Navigation("EstadoCidades");
                });

            modelBuilder.Entity("FichaOnline.Models.TBFicha", b =>
                {
                    b.Navigation("FichaCatOpcResp");

                    b.Navigation("FichaFichaProv");
                });

            modelBuilder.Entity("FichaOnline.Models.TBPerfilaAcesso", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("FichaOnline.Models.TBPolo", b =>
                {
                    b.Navigation("UnidadePolos");
                });

            modelBuilder.Entity("FichaOnline.Models.TBUnidadeTipos", b =>
                {
                    b.Navigation("UnidadeUnidadeTipos");
                });

            modelBuilder.Entity("FichaOnline.Models.TBUnidades", b =>
                {
                    b.Navigation("UnidadeUsuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
