// <auto-generated />
using System;
using FichaOnline.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FichaOnline.Migrations
{
    [DbContext(typeof(DataBaseContext))]
    [Migration("20231022015201_Criacao-das-tabelas-intermediaris")]
    partial class Criacaodastabelasintermediaris
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FichaOnline.Models.TBPolo", b =>
                {
                    b.Property<int>("PoloId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PoloId"));

                    b.Property<DateTime?>("PoloAltEm")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PoloAltPor")
                        .HasColumnType("int");

                    b.Property<DateTime>("PoloIncEm")
                        .HasColumnType("datetime2");

                    b.Property<int>("PoloIncPor")
                        .HasColumnType("int");

                    b.Property<string>("PoloNome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PoloStatus")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PoloId");

                    b.ToTable("TBPOLO");
                });

            modelBuilder.Entity("FichaOnline.Models.TBPolounidades", b =>
                {
                    b.Property<int>("PoloId")
                        .HasColumnType("int");

                    b.Property<int>("UnidadeId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PoloUnidAltEm")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PoloUnidAltPor")
                        .HasColumnType("int");

                    b.Property<int>("PoloUnidId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PoloUnidIncEm")
                        .HasColumnType("datetime2");

                    b.Property<int>("PoloUnidIncPor")
                        .HasColumnType("int");

                    b.Property<string>("PoloUnidTipo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PoloId", "UnidadeId");

                    b.HasIndex("UnidadeId");

                    b.ToTable("TBPOLOUNIDADES");
                });

            modelBuilder.Entity("FichaOnline.Models.TBUnidadeTipos", b =>
                {
                    b.Property<int>("UnidadeTpoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UnidadeTpoId"));

                    b.Property<string>("UnidadeSgl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnidadeTipo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UnidadeTpoAltEm")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UnidadeTpoAltPor")
                        .HasColumnType("int");

                    b.Property<string>("UnidadeTpoDsc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UnidadeTpoIncEm")
                        .HasColumnType("datetime2");

                    b.Property<int>("UnidadeTpoIncPor")
                        .HasColumnType("int");

                    b.HasKey("UnidadeTpoId");

                    b.ToTable("TBUNIDADETIPOS");
                });

            modelBuilder.Entity("FichaOnline.Models.TBUnidades", b =>
                {
                    b.Property<int>("UnidadeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UnidadeId"));

                    b.Property<int>("PoloId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UnidadeAltEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("UnidadeAltPor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnidadeCEP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UnidadeCod")
                        .HasColumnType("int");

                    b.Property<string>("UnidadeDDD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnidadeDesc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnidadeEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnidadeEndComp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnidadeEndLog")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnidadeEndNmr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnidadeFone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UnidadeIncEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("UnidadeIncPor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnidadeStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UnidadesTpoId")
                        .HasColumnType("int");

                    b.HasKey("UnidadeId");

                    b.HasIndex("PoloId");

                    b.HasIndex("UnidadesTpoId");

                    b.ToTable("TBUNIDADES");
                });

            modelBuilder.Entity("FichaOnline.Models.TBUsuarios", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuarioId"));

                    b.Property<int>("PerfilAcessoId")
                        .HasColumnType("int");

                    b.Property<int>("UnidadeId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UsuarioAltEm")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UsuarioAltPor")
                        .HasColumnType("int");

                    b.Property<string>("UsuarioCpf")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("UsuarioEmailTran")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("UsuarioIncEm")
                        .HasColumnType("datetime2");

                    b.Property<int>("UsuarioIncPor")
                        .HasColumnType("int");

                    b.Property<string>("UsuarioNome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioSenha")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UsuarioSenhaTemp")
                        .HasColumnType("int");

                    b.Property<string>("UsuarioStatus")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UsuarioId");

                    b.HasIndex("PerfilAcessoId");

                    b.HasIndex("UnidadeId");

                    b.ToTable("TBUSUARIOS");
                });

            modelBuilder.Entity("FichaOnline.Models.Tbperfilacesso", b =>
                {
                    b.Property<int>("PerfilAcessoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PerfilAcessoId"));

                    b.Property<DateTime?>("PerfilAcessoAltEm")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PerfilAcessoAltPor")
                        .HasColumnType("int");

                    b.Property<string>("PerfilAcessoDesc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PerfilAcessoIncEm")
                        .HasColumnType("datetime2");

                    b.Property<int>("PerfilAcessoIncPor")
                        .HasColumnType("int");

                    b.Property<short>("PerfilAcessoNivel")
                        .HasColumnType("smallint");

                    b.HasKey("PerfilAcessoId");

                    b.ToTable("TBPERFILACESSO");
                });

            modelBuilder.Entity("FichaOnline.Models.TBPolounidades", b =>
                {
                    b.HasOne("FichaOnline.Models.TBPolo", "Polo")
                        .WithMany("PoloUnidades")
                        .HasForeignKey("PoloId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FichaOnline.Models.TBUnidades", "Unidade")
                        .WithMany()
                        .HasForeignKey("UnidadeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Polo");

                    b.Navigation("Unidade");
                });

            modelBuilder.Entity("FichaOnline.Models.TBUnidades", b =>
                {
                    b.HasOne("FichaOnline.Models.TBPolo", "Polo")
                        .WithMany("Unidades")
                        .HasForeignKey("PoloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FichaOnline.Models.TBUnidadeTipos", "TiposUnidade")
                        .WithMany("Unidade")
                        .HasForeignKey("UnidadesTpoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Polo");

                    b.Navigation("TiposUnidade");
                });

            modelBuilder.Entity("FichaOnline.Models.TBUsuarios", b =>
                {
                    b.HasOne("FichaOnline.Models.Tbperfilacesso", "PerfilAcesso")
                        .WithMany("Usuarios")
                        .HasForeignKey("PerfilAcessoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FichaOnline.Models.TBUnidades", "Unidades")
                        .WithMany("Usuarios")
                        .HasForeignKey("UnidadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PerfilAcesso");

                    b.Navigation("Unidades");
                });

            modelBuilder.Entity("FichaOnline.Models.TBPolo", b =>
                {
                    b.Navigation("PoloUnidades");

                    b.Navigation("Unidades");
                });

            modelBuilder.Entity("FichaOnline.Models.TBUnidadeTipos", b =>
                {
                    b.Navigation("Unidade");
                });

            modelBuilder.Entity("FichaOnline.Models.TBUnidades", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("FichaOnline.Models.Tbperfilacesso", b =>
                {
                    b.Navigation("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
