// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FichaOnline.Models;

public partial class Tbalunosala
{
    public int AluSalaId { get; set; }

    public int AluId { get; set; }

    public string AluSalaTurno { get; set; }

    public string AluSalaSerieDesc { get; set; }

    public int AluSalaIncPor { get; set; }

    public DateTime AluSalaIncEm { get; set; }

    public int? AluSalaAltPor { get; set; }

    public DateTime? AluSalaAltEm { get; set; }

    public virtual Tbaluno Alu { get; set; }
}