// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FichaOnline.Models;

public partial class Tbaluno
{
    public int AluId { get; set; }

    public string AluNom { get; set; }

    public string AluNomSoc { get; set; }

    public DateTime AluDtaNasc { get; set; }

    public string AluCpf { get; set; }

    public string AluSexo { get; set; }

    public string AluFiliacao1 { get; set; }

    public string AluFiliacao2 { get; set; }

    public string AluFiliacao3 { get; set; }

    public long? AluIdinep { get; set; }

    public int AluRaca { get; set; }

    public int? AluEndEstId { get; set; }

    public string AluEndLog { get; set; }

    public string AluEndNmrLog { get; set; }

    public string AluEndCmpLog { get; set; }

    public string AluEndBairro { get; set; }

    public string AluEndCep { get; set; }

    public int AluEndCidId { get; set; }

    public string AluTelResDdd { get; set; }

    public string AluTelRes { get; set; }

    public string AluTelCelDdd { get; set; }

    public string AluTelCel { get; set; }

    public string AluTelConDdd { get; set; }

    public string AluTelCon { get; set; }

    public string AluObs { get; set; }

    public string AluImportado { get; set; }

    public string AluStatus { get; set; }

    public int AluIncPor { get; set; }

    public DateTime AluIncEm { get; set; }

    public int? AluAltPor { get; set; }

    public DateTime? AluAltEm { get; set; }

    public int? AluEndBairroId { get; set; }

    public decimal? GedAluCod { get; set; }

    public virtual Tbcidade AluEndCid { get; set; }

    public virtual ICollection<Tbalunosala> Tbalunosala { get; set; } = new List<Tbalunosala>();

    public virtual ICollection<Tbfichaficai> Tbfichaficai { get; set; } = new List<Tbfichaficai>();
}