// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FichaOnline.Models;

public partial class Tbalunoserie
{
    public int AluSerieId { get; set; }

    public string AluSerieDesc { get; set; }

    public string AluSerieSts { get; set; }

    public int AluSerieIncPor { get; set; }

    public DateTime AluSerieIncEm { get; set; }

    public int? AluSerieAltPor { get; set; }

    public DateTime? AluSerieAltEm { get; set; }
}