// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FichaOnline.Models;

public partial class Tbbairro
{
    public int BairroId { get; set; }

    public string BairroNome { get; set; }

    public int BairroCidId { get; set; }

    public int? BairroIncPor { get; set; }

    public int BairroAltPor { get; set; }

    public DateTime? BairroIncEm { get; set; }

    public DateTime BairroAltEm { get; set; }

    public virtual Tbcidade BairroCid { get; set; }

    public virtual ICollection<Tbconselho> Tbconselho { get; set; } = new List<Tbconselho>();

    public virtual ICollection<Tbconselhobairros> Tbconselhobairros { get; set; } = new List<Tbconselhobairros>();

    public virtual ICollection<Tbministerio> Tbministerio { get; set; } = new List<Tbministerio>();
}