// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FichaOnline.Models;

public partial class Tbcidade
{
    public int CidId { get; set; }

    public string CidNom { get; set; }

    public string CidEstSgl { get; set; }

    public string CidEstNom { get; set; }

    public long? CidCodIbge { get; set; }

    public int? CidTipo { get; set; }

    public int? CidIdDistrito { get; set; }

    public string CidNomDistrito { get; set; }

    public int CidIncPor { get; set; }

    public DateTime CidIncEm { get; set; }

    public int? CidAltPor { get; set; }

    public DateTime? CidAltEm { get; set; }

    public virtual ICollection<Tbaluno> Tbaluno { get; set; } = new List<Tbaluno>();

    public virtual ICollection<Tbbairro> Tbbairro { get; set; } = new List<Tbbairro>();
}