// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FichaOnline.Models;

public partial class Tbconselhobairros
{
    public int ConselhoId { get; set; }

    public int ConselhoBairroId { get; set; }

    public string ConsBairroStatus { get; set; }

    public int ConsBairroIncPor { get; set; }

    public DateTime ConsBairroIncEm { get; set; }

    public int? ConsBairroAltPor { get; set; }

    public DateTime? ConsBairroAltEm { get; set; }

    public virtual Tbconselho Conselho { get; set; }

    public virtual Tbbairro ConselhoBairro { get; set; }
}