// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FichaOnline.Models;

public partial class Tbconselho
{
    public int ConselhoId { get; set; }

    public string ConselhoNome { get; set; }

    public string ConselhoStatus { get; set; }

    public string ConselhoEmail { get; set; }

    public string ConselhoDdd { get; set; }

    public string ConselhoFone { get; set; }

    public int ConselhoIncPor { get; set; }

    public DateTime ConselhoIncEm { get; set; }

    public int ConselhoAltPor { get; set; }

    public DateTime ConselhoAltEm { get; set; }

    public int? ConselhoEndBairroId { get; set; }

    public string ConselhoEndNmr { get; set; }

    public string ConselhoEndLog { get; set; }

    public string ConselhoTipoAtendimento { get; set; }

    public virtual Tbbairro ConselhoEndBairro { get; set; }

    public virtual ICollection<Tbconselhobairros> Tbconselhobairros { get; set; } = new List<Tbconselhobairros>();
}