// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FichaOnline.Models;

public partial class TbdashBoard
{
    public decimal DashBoardPolo { get; set; }

    public decimal DashBoardOrgao { get; set; }

    public decimal DashBoardEscola { get; set; }

    public decimal DashBoardBairro { get; set; }

    public decimal DashBoardCidade { get; set; }

    public string DashBoardOrgaoNome { get; set; }

    public string DashBoardPoloNome { get; set; }

    public string DashBoardOrgaoTipo { get; set; }

    public string DashBoardEscolaNome { get; set; }

    public string DashBoardBairroNome { get; set; }

    public string DashBoardCidadeNome { get; set; }

    public decimal DashBoardQtde { get; set; }
}