// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FichaOnline.Models;

public partial class Tbdiretoriaregionalcidades
{
    public decimal DiretoriaRegionalId { get; set; }

    public decimal DiretoriaRegionalCidadesCidId { get; set; }

    public string DiretoriaRegionalCidadesStatus { get; set; }

    public DateTime DiretoriaRegionalCidadesAltEm { get; set; }

    public int DiretoriaRegionalCidadesAltPor { get; set; }

    public DateTime DiretoriaRegionalCidadesIncEm { get; set; }

    public int DiretoriaRegionalCidadesIncPor { get; set; }

    public virtual TbdiretoriaRegional DiretoriaRegional { get; set; }
}