// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FichaOnline.Models;

public partial class TbdiretoriaRegional
{
    public decimal DiretoriaRegionalId { get; set; }

    public string DiretoriaRegionalStatus { get; set; }

    public string DiretoriaRegionalEmail { get; set; }

    public string DiretoriaRegionalDdd { get; set; }

    public string DiretoriaRegionalFone { get; set; }

    public string DiretoriaRegionalEndLog { get; set; }

    public string DiretoriaRegionalEndNmr { get; set; }

    public decimal? DiretoriaRegionalEndBairroId { get; set; }

    public decimal DiretoriaRegionalEndBairroCidI { get; set; }

    public int DiretoriaRegionalIncPor { get; set; }

    public DateTime DiretoriaRegionalIncEm { get; set; }

    public int DiretoriaRegionalAltPor { get; set; }

    public DateTime DiretoriaRegionalAltEm { get; set; }

    public string DiretoriaRegionalNome { get; set; }

    public virtual ICollection<Tbdiretoriaregionalcidades> Tbdiretoriaregionalcidades { get; set; } = new List<Tbdiretoriaregionalcidades>();
}