// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FichaOnline.Models;

public partial class Tbescola
{
    public int EscId { get; set; }

    public int? EscCod { get; set; }

    public string EscNom { get; set; }

    public string EscEndLog { get; set; }

    public string EscEndNmrLog { get; set; }

    public string EscEndCmpLog { get; set; }

    public string EscEndBairro { get; set; }

    public string EscEndCep { get; set; }

    public int? EscEstId { get; set; }

    public int EscEndCidId { get; set; }

    public string EscEndCidNom { get; set; }

    public string EscTelDdd { get; set; }

    public string EscTel { get; set; }

    public string EscEmail { get; set; }

    public string EscTipo { get; set; }

    public string EscStatus { get; set; }

    public string EscImportada { get; set; }

    public int EscIncPor { get; set; }

    public DateTime EscIncEm { get; set; }

    public int? EscAltPor { get; set; }

    public DateTime? EscAltEm { get; set; }

    public int? EscEndBairroId { get; set; }

    public string EscCategoria { get; set; }

    public virtual ICollection<TBFicha> Tbfichaficai { get; set; } = new List<TBFicha>();
}