// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FichaOnline.Models;

public partial class Tbestado
{
    public int EstId { get; set; }

    public string EstSgl { get; set; }

    public string EstNom { get; set; }

    public int EstIncPor { get; set; }

    public DateTime EstIncEm { get; set; }

    public int? EstAltPor { get; set; }

    public DateTime? EstAltEm { get; set; }
}