// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FichaOnline.Models;

public partial class Tbfichaficai
{
    public int FicaiId { get; set; }

    public int FichaCatId { get; set; }

    public int FichaModId { get; set; }

    public int? FichaStsId { get; set; }

    public int? FichaOrgCod { get; set; }

    public string FicaiNovo { get; set; }

    public int AluId { get; set; }

    public int EscId { get; set; }

    public DateTime FicaiDtaIni { get; set; }

    public DateTime? FicaiDtaFim { get; set; }

    public int FicaiIncPor { get; set; }

    public DateTime FicaiIncEm { get; set; }

    public int? FicaiAltPor { get; set; }

    public DateTime FicaiAltEm { get; set; }

    public string FichaOrgTipo { get; set; }

    public virtual Tbaluno Alu { get; set; }

    public virtual Tbescola Esc { get; set; }

    public virtual Tbfichacategoria FichaCat { get; set; }

    public virtual Tbfichamodelo FichaMod { get; set; }
}