//// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
//#nullable disable
//using System;
//using System.Collections.Generic;

//namespace FichaOnline.Models;

//public partial class Tbfichastatus
//{
//    public int FichaStsId { get; set; }

//    public string FichaStsTitulo { get; set; }

//    public string FichaStsOrgTipo { get; set; }

//    public string FichaSts { get; set; }

//    public string FichaStsFim { get; set; }

//    public string FichaStsInicial { get; set; }

//    public int FichaStsIncPor { get; set; }

//    public DateTime FichaStsIncEm { get; set; }

//    public int? FichaStsAltPor { get; set; }

//    public DateTime? FichaStsAltEm { get; set; }

//    public virtual ICollection<Tbhiststatusperfilacesso> Tbhiststatusperfilacesso { get; set; } = new List<Tbhiststatusperfilacesso>();

//    public virtual ICollection<Tbstatusperfilacesso> Tbstatusperfilacesso { get; set; } = new List<Tbstatusperfilacesso>();
//}