// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FichaOnline.Models;

public partial class Tbfichamodelo
{
    public int FichaModId { get; set; }

    public string FichaModTitulo { get; set; }

    public string FichaModSts { get; set; }

    public int FichaModIncPor { get; set; }

    public DateTime FichaModIncEm { get; set; }

    public int? FichaModAltPor { get; set; }

    public DateTime? FichaModAltEm { get; set; }

    public virtual ICollection<Tbfichaficai> Tbfichaficai { get; set; } = new List<Tbfichaficai>();
}