// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FichaOnline.Models;

public partial class Tbfichacategoria
{
    public int FichaCatId { get; set; }

    public string FichaCatTitulo { get; set; }

    public string FichaCatSts { get; set; }

    public int FichaCatIncPor { get; set; }

    public DateTime FichaCatIncEm { get; set; }

    public int? FichaCatAltPor { get; set; }

    public DateTime? FichaCatAltEm { get; set; }

    public virtual ICollection<TBFicha> Tbfichaficai { get; set; } = new List<TBFicha>();

    public virtual ICollection<Tbhiststatusperfilacesso> Tbhiststatusperfilacesso { get; set; } = new List<Tbhiststatusperfilacesso>();

    public virtual ICollection<Tbparmprazo> Tbparmprazo { get; set; } = new List<Tbparmprazo>();

    public virtual ICollection<Tbstatusperfilacesso> Tbstatusperfilacesso { get; set; } = new List<Tbstatusperfilacesso>();

    public virtual ICollection<Tbtramite> Tbtramite { get; set; } = new List<Tbtramite>();
}