// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FichaOnline.Models;

public partial class Tbfichaitemopcao
{
    public int FichaItemOpcId { get; set; }

    public string FichaItemOpcDesc { get; set; }

    public int FichaItemId { get; set; }

    public int FichaItemOpcIncPor { get; set; }

    public int? FichaItemOpcAltPor { get; set; }

    public DateTime FichaItemOpcIncEm { get; set; }

    public DateTime? FichaItemOpcAltEm { get; set; }
}