// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FichaOnline.Models;

public partial class Tbhistparm
{
    public int HistParmId { get; set; }

    public int HistParametroId { get; set; }

    public string HistParametroTitulo { get; set; }

    public string HistParametroValor { get; set; }

    public int HistParmIncPor { get; set; }

    public DateTime HistParmIncEm { get; set; }
}