//// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
//#nullable disable
//using System;
//using System.Collections.Generic;

//namespace FichaOnline.Models;

//public partial class Tbhiststatusperfilacesso
//{
//    public int HistStatusAcessoId { get; set; }

//    public int PerfilAcessoId { get; set; }

//    public int FichaCatId { get; set; }

//    public int FichaStsId { get; set; }

//    public int HistStatusOrgCod { get; set; }

//    public int? HistStatusIncPor { get; set; }

//    public DateTime HistStatusIncEm { get; set; }

//    public virtual TBCategoria FichaCat { get; set; }

//    public virtual Tbfichastatus FichaSts { get; set; }

//    public virtual TBPerfilaAcesso PerfilAcesso { get; set; }
//}