// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FichaOnline.Models;

public partial class Tbhistficai
{
    public int HistFicaiCodId { get; set; }

    public int HistFicaiId { get; set; }

    public int? HistFichaStsId { get; set; }

    public int HistFichaCatId { get; set; }

    public int? HistOrgCod { get; set; }

    public int HistFicaiIncPor { get; set; }

    public DateTime HistFicaiIncEm { get; set; }

    public string HistOrgTipo { get; set; }
}