// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FichaOnline.Models;

public partial class Tbmenuperfilacesso
{
    public int MenuPerfilAcessoId { get; set; }

    public int PerfilAcessoId { get; set; }

    public int MenuId { get; set; }

    public int? MenuPerfilAcessoIncPor { get; set; }

    public DateTime MenuPerfilAcessoIncEm { get; set; }

    public int? MenuPerfilAcessoAltPor { get; set; }

    public DateTime MenuPerfilAcessoAltEm { get; set; }

    public virtual Tbmenu Menu { get; set; }

    public virtual TBPerfilacesso PerfilAcesso { get; set; }
}