// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FichaOnline.Models;

public partial class Tbmenu
{
    public int MenuId { get; set; }

    public int? MenuPai { get; set; }

    public string MenuTitulo { get; set; }

    public string MenuLink { get; set; }

    public short MenuOrdem { get; set; }

    public string MenuStatus { get; set; }

    public byte[] MenuImg { get; set; }

    public string MenuImgLocal { get; set; }

    public string MenuImgNome { get; set; }

    public string MenuImgTipo { get; set; }

    public int MenuIncPor { get; set; }

    public int? MenuAltPor { get; set; }

    public DateTime MenuIncEm { get; set; }

    public DateTime? MenuAltEm { get; set; }

    public virtual ICollection<Tbmenuperfilacesso> Tbmenuperfilacesso { get; set; } = new List<Tbmenuperfilacesso>();
}