// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FichaOnline.Models;

public partial class Tbministerio
{
    public int MinisterioId { get; set; }

    public string MinisterioNome { get; set; }

    public string MinisterioStatus { get; set; }

    public string MinisterioEmail { get; set; }

    public string MinisterioDdd { get; set; }

    public string MinisterioFone { get; set; }

    public int MinisterioIncPor { get; set; }

    public DateTime MinisterioIncEm { get; set; }

    public int MinisterioAltPor { get; set; }

    public DateTime MinisterioAltEm { get; set; }

    public int? MinisterioEndBairroId { get; set; }

    public string MinisterioEndNmr { get; set; }

    public string MinisterioEndLog { get; set; }

    public virtual Tbbairro MinisterioEndBairro { get; set; }
}