// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FichaOnline.Models;

public partial class Tbministeriocidades
{
    public decimal MinisterioId { get; set; }

    public decimal MinisterioCidadesCidId { get; set; }

    public string MinisterioCidadesStatus { get; set; }

    public DateTime MinisterioCidadesAltEm { get; set; }

    public int MinisterioCidadesAltPor { get; set; }

    public DateTime MinisterioCidadesIncEm { get; set; }

    public int MinisterioCidadesIncPor { get; set; }
}