// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FichaOnline.Models;

public partial class Tbparmprazo
{
    public int ParmPrazoId { get; set; }

    public int ParmPerfilAcessoId { get; set; }

    public int ParmPerfilAcessoNivel { get; set; }

    public int FichaCatId { get; set; }

    public int ParmPrazoDias { get; set; }

    public int ParmPrazoIncPor { get; set; }

    public DateTime ParmPrazoIncEm { get; set; }

    public int ParmPrazoAltPor { get; set; }

    public DateTime ParmPrazoAltEm { get; set; }

    public virtual TBCategoria FichaCat { get; set; }
}