// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FichaOnline.Models;

public partial class Tbparametro
{
    public int ParametroId { get; set; }

    public string ParametroTitulo { get; set; }

    public string ParametroValor { get; set; }

    public int ParametroIncPor { get; set; }

    public DateTime ParametroIncEm { get; set; }

    public int? ParametroAltPor { get; set; }

    public DateTime? ParametroAltEm { get; set; }
}