// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FichaOnline.Models;

public partial class Tbpoloorgao
{
    public int PoloOrgaoId { get; set; }

    public int PoloId { get; set; }

    public int PoloOrgaoOrgCod { get; set; }

    public string PoloOrgaoOrgTipo { get; set; }

    public int PoloOrgaoIncPor { get; set; }

    public DateTime PoloOrgaoIncEm { get; set; }

    public int? PoloOrgaoAltPor { get; set; }

    public DateTime PoloOrgaoAltEm { get; set; }

    public virtual Tbpolo Polo { get; set; }
}