// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FichaOnline.Models;

public partial class Tbpolo
{
    public int PoloId { get; set; }

    public string PoloNome { get; set; }

    public string PoloSts { get; set; }

    public int PoloIncPor { get; set; }

    public DateTime PoloIncEm { get; set; }

    public int? PoloAltPor { get; set; }

    public DateTime PoloAltEm { get; set; }

    public virtual ICollection<Tbpoloorgao> Tbpoloorgao { get; set; } = new List<Tbpoloorgao>();
}