// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FichaOnline.Models;

public partial class Tbpolomodelo
{
    public int PoloModeloId { get; set; }

    public int PoloModeloPoloId { get; set; }

    public int PoloModeloFichaModId { get; set; }

    public int PoloModeloIncPor { get; set; }

    public DateTime PoloModeloIncEm { get; set; }

    public int? PoloModeloAltPor { get; set; }

    public DateTime PoloModeloAltEm { get; set; }
}