// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FichaOnline.Models;

public partial class Tbstatusperfilacesso
{
    public int StatusPerfilAcessoId { get; set; }

    public int PerfilAcessoId { get; set; }

    public int FichaCatId { get; set; }

    public int FichaStsId { get; set; }

    public string StatusPerfilAcessoAlterar { get; set; }

    public int? StatusPerfilAcessoIncPor { get; set; }

    public DateTime StatusPerfilAcessoIncEm { get; set; }

    public int? StatusPerfilAcessoAltPor { get; set; }

    public DateTime StatusPerfilAcessoAltEm { get; set; }

    public virtual TBCategoria FichaCat { get; set; }

    public virtual Tbfichastatus FichaSts { get; set; }

    public virtual TBPerfilaAcesso PerfilAcesso { get; set; }
}