// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FichaOnline.Models;

public partial class Tbtramite
{
    public int TramiteId { get; set; }

    public int PerfilAcessoId { get; set; }

    public int FichaCatId { get; set; }

    public int TramiteAtual { get; set; }

    public int TramiteDestino { get; set; }

    public int TramiteIncPor { get; set; }

    public DateTime TramiteIncEm { get; set; }

    public virtual TBCategoria FichaCat { get; set; }

    public virtual TBPerfilacesso PerfilAcesso { get; set; }
}